### ISSUE TITLE
How can i disable not required metrics?

### ISSUE THREAD

**Issue by mpostument** [opencost/opencost-helm-chart#102]
Hello, i see that opencost support metrics disabling https://github.com/opencost/opencost/blob/c324846753beda858a1ea18a00fc50b5ca509309/pkg/metrics/metricsconfig.go#L24

But i don't see how this can be done using chart. Is there a way to do it?

**Comment by mattray** [comment]
I haven't seen that documented before but I'd love to get it added to both the documentation and Helm chart.

**Comment by mpostument** [comment]
Any updates on this?

In kubecost helm chart i was able to specify something like this

```yaml
  prometheus:
    nodeExporter:
      enabled: false
    kubeStateMetrics:
      enabled: false
    kube-state-metrics:
      disabled: true

  kubecostMetrics:
    emitKsmV1Metrics: false
    emitKsmV1MetricsOnly: true
```

Which disable metrics emitting. Is there a way to do the same here?

**Comment by mattray** [comment]
Would that go in the Prometheus configuration? The OpenCost Helm chart doesn't currently deploy Prometheus (Kubecost does), so maybe we'd need to alternate configs for Prometheus?
https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/prometheus/extraScrapeConfigs.yaml

**Comment by mpostument** [comment]
I was able to do it by setting this environment variables 

```yaml
        EMIT_KSM_V1_METRICS: "false"
        EMIT_KSM_V1_METRICS_ONLY: "true"
```

**Comment by asdfgugus** [comment]
It could be adapted from the [cost-analyzer-helm-chart](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L764-L777):
```YAML           
{{- if .Values.kubecostMetrics }}
- name: EMIT_POD_ANNOTATIONS_METRIC
  value: {{ (quote .Values.kubecostMetrics.emitPodAnnotations) | default (quote false) }}
- name: EMIT_NAMESPACE_ANNOTATIONS_METRIC
  value: {{ (quote .Values.kubecostMetrics.emitNamespaceAnnotations) | default (quote false) }}
{{- end }}
{{- if .Values.kubecostMetrics }}
- name: EMIT_KSM_V1_METRICS
  value: {{ (quote .Values.kubecostMetrics.emitKsmV1Metrics) | default (quote true) }}
{{- end }}
{{- if .Values.kubecostMetrics }}
- name: EMIT_KSM_V1_METRICS_ONLY # ONLY emit KSM v1 metrics that do not exist in KSM 2 by default
  value: {{ (quote .Values.kubecostMetrics.emitKsmV1MetricsOnly) | default (quote false) }}
{{- end }}
```

**Comment by mattray** [comment]
I didn't realize those were in the [OpenCost codebase](https://github.com/opencost/opencost/blob/develop/pkg/env/costmodelenv.go#L50). You should be able to add those to [opencost.exporter.env](https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml#L185) in your `values.yaml`, but a separate PR for specifying them would be worthwhile too.

**Comment by asdfgugus** [comment]
If this configuration is desired via helm chart, I can add it to the deployment template. So it would be configurable like this:
```YAML
opencostMetrics:
  emitPodAnnotations: false
  emitNamespaceAnnotations: false
  emitKsmV1Metrics: true
  emitKsmV1MetricsOnly: false
```

**Comment by mattray** [comment]
I'd approve it and add it to the docs.

**Comment by asdfgugus** [comment]
I just created a [draft PR](https://github.com/opencost/opencost-helm-chart/pull/182).

**Comment by asdfgugus** [comment]
@mpostument the change got released in [1.32.0](https://github.com/opencost/opencost-helm-chart/releases/tag/1.32.0-helm). 

You can now configure it like this:
```YAML
opencost:
  metrics:
    kubeStateMetrics:
      emitPodAnnotations: ""
      emitNamespaceAnnotations: ""
      emitKsmV1Metrics: "" 
      emitKsmV1MetricsOnly: ""
```
