### ISSUE TITLE
Support arguments to the exporter container such as `--log-level`

### ISSUE THREAD

**Issue by kitforbes** [opencost/opencost-helm-chart#103]
It would be great if you could add support for setting command-line flags when calling OpenCost. The currently available flags can be seen here: https://github.com/opencost/opencost/blob/3186c1eee8de0826e44f0b13d00bf06f86db787e/pkg/cmd/commands.go#L73-L75

This is useful for setting the log level of OpenCost when trying to identify a problem. For example, the current deployment can be editted with the following to set the log level to `trace`.

```yml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: opencost
        args:
        - --log-level
        - trace
```
