### ISSUE TITLE
Instance/Node label duplicated for Node IP and name

### ISSUE THREAD

**Issue by MuriloCouceiro** [opencost/opencost-helm-chart#115]
### Description

I've installed the OpenCost helm chart 1.18.0 with the following values

```
opencost:
    nodeSelector:
      kubernetes.io/os: linux
    metrics:
      serviceMonitor:
        enabled: true
    exporter: 
      extraEnv: 
        EMIT_KSM_V1_METRICS_ONLY: true  
        EMIT_KSM_V1_METRICS: false
        # The default config path is read only, for customizing we have to swap spots.
        CONFIG_PATH: "/tmp/custom-config"

      extraVolumeMounts:
        - mountPath: /tmp/custom-config
          name: custom-configs
    prometheus: 
      internal:
        enabled: true
        serviceName: svcname
        namespaceName: monitoring
        port: 9090
    ui: 
      enabled: true
      ingress: 
        enabled: true
        ingressClassName: "nginx"
        # -- Annotations for Ingress resource
        annotations: {}
          # kubernetes.io/tls-acme: "true"
        # -- A list of host rules used to configure the Ingress
        # @default -- See [values.yaml](values.yaml)
        hosts:
          - host: _____
            paths:
              - /
  extraVolumes:
  - name: custom-configs
    configMap:
      name: opencost-conf
```

The extra Configmap is used to disable the v1 kube state metrics.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: opencost-conf
data:
    default.json: |
        {
            "provider": "custom",
            "description": "Default prices based on GCP us-central1",
            "CPU": "0.031611",
            "spotCPU": "0.006655",
            "RAM": "0.004237",
            "spotRAM": "0.000892",
            "GPU": "0.95",
            "storage": "0.00005479452",
            "zoneNetworkEgress": "0.01",
            "regionNetworkEgress": "0.01",
            "internetNetworkEgress": "0.12"
        }
    metrics.json: | 
        {
            "disabledMetrics":[
                "kube_pod_owner",
                "kube_pod_labels",
                "kube_namespace_labels",
                "kube_node_labels",
                "kube_node_status_condition"
                ]
        }
        

```

For metrics, I'm using kube-prometheus-stack (with node-exporter and kube-state-metrics). 

### Problem

The cost model is exporting metrics for the same node with different instance/node labels (one for the node IP and another with the node name). This is a problem because the node_**_cost metrics have the node label value as the node name and the cost model ends up discarding the metrics with the IP. 
This image shows Node Exporter containers, but this happens for almost every pod/container. 

##### OpenCost UI
![image](https://github.com/opencost/opencost-helm-chart/assets/72820316/4524a1f6-1d04-4499-992a-45f14502bf52)

##### Prometheus
![image](https://github.com/opencost/opencost-helm-chart/assets/72820316/7676daca-e7ee-4075-a853-585537a09aa5) 

I'm I doing anything wrong?
Can anyone help me understand which metrics the cost model looks at?
