### ISSUE TITLE
Athena configuration incomplete

### ISSUE THREAD

**Issue by sossickd** [opencost/opencost-helm-chart#127]
**Describe the bug**
Error in pod logs after following AWS integration instructions for OpenCost and KubeCost for Athena integration.

**To Reproduce**
1. Configure config map below.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: opencost-aws
  namespace: opencost
data:
  aws.json: |
    {
        "provider": "aws",
        "description": "AWS Provider Configuration. Provides default values used if instance type or spot information is not found.",
        "CPU": "0.031611",
        "spotCPU": "0.006655",
        "RAM": "0.004237",
        "GPU": "0.95",
        "spotRAM": "0.000892",
        "storage": "0.000138888889",
        "zoneNetworkEgress": "0.01",
        "regionNetworkEgress": "0.01",
        "internetNetworkEgress": "0.143",
        "spotLabel": "kops.k8s.io/instancegroup",
        "spotLabelValue": "spotinstance-nodes",
        "awsSpotDataRegion":"eu-west-1",
        "awsSpotDataBucket": "iobspotdatafeedsubscription",
        "awsSpotDataPrefix": "spot-datafeed",
        "athenaBucketName": "s3://aws-athena-query-results-REDACTED-eu-west-1",
        "athenaRegion": "eu-west-1",
        "athenaDatabase": "athenacurcfn_opencost_report",
        "athenaTable": "opencost_report",
        "projectID": "REDACTED"
    }
```

2. Install opencost on AKS using helm chart

Extract of the values.yaml that configures the configmap.

```
opencost:
  exporter:
    extraEnv:
      CONFIG_PATH: "/tmp/custom-config"
    extraVolumeMounts:
      - mountPath: /tmp/custom-config
        name: custom-configs

extraVolumes:
  - name: custom-configs
    configMap:
      name: opencost-aws
```

3. View pod logs and see the following errors.

```
2023-10-13T09:59:20.927916579Z ERR Failed to lookup reserved instance data: no reservation data available in Athena
2023-10-13T09:59:20.927937945Z ERR Failed to lookup savings plan data: Error fetching Savings Plan Data: QueryAthenaPaginated: athena configuration incomplete
```

**Expected behavior**
Athena integration should work according to the [Kubecost documents](https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations)

**Which version of OpenCost are you using?**
Helm chart version 1.20.1
Opencost App Version 1.106.2
