### ISSUE TITLE
Additional labels are not assigned to a services monitor based on values.yaml config

### ISSUE THREAD

**Issue by andriktr** [opencost/opencost-helm-chart#13]
Hey, 
Noticed that `additionalLabels`  has no effect to servicemonitor.yaml template labels
```yaml
  metrics:
    serviceMonitor:
      enabled: false
      additionalLabels: {}
      ## The label to use to retrieve the job name from.
      ## jobLabel: "app.kubernetes.io/name"
      namespace: ''
      namespaceSelector: {}
      ## Default: scrape .Release.Namespace only
      ## To scrape all, use the following:
      ## namespaceSelector:
      ##   any: true
      scrapeInterval: 30s
      # honorLabels: true
      targetLabels: []
      relabelings: []
      metricRelabelings: []
```

Curently service monitor template contains the following regarding labels:
```yaml
...
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
```

Need to add something like this:

```yaml
...
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
    {{- if .Values.opencost.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.opencost.metrics.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
```
