### ISSUE TITLE
Opencost grafana dashboard partly not working

### ISSUE THREAD

**Issue by andriktr** [opencost/opencost-helm-chart#134]
Hi,
I'm trying to use the following grafana https://github.com/opencost/opencost-helm-chart/blob/main/examples/dashboard/kube-prometheus-stack-opencost-dashboard.json dashboard to view opencost data. In my case it's only working partly and some boards throws the following errors:
<img width="1946" alt="image" src="https://github.com/opencost/opencost/assets/25537180/5475b8fe-b690-4851-8e8c-5e0534262f1e">

<img width="1428" alt="image" src="https://github.com/opencost/opencost/assets/25537180/71c99a08-40b1-4221-80e6-686b51bde6d0">

Any thoughts? 

Thanks in advance.

**Comment by mattray** [comment]
@andriktr I'll try to recreate and see what I find. I'm moving it over to the opencost-helm-chart repository since that's where it originated.

**Comment by andriktr** [comment]
@mattray Thanks a lot.

**Comment by sossickd** [comment]
I am also getting the same partial success with the grafana dashboard. If it helps the partial success in on a AWS EKS cluster and am not experiencing the issue on an Azure AKS cluster.

**Comment by sossickd** [comment]
Scape my last comment the dashboard is now partially working on an AKS cluster that was previously working

**Comment by sossickd** [comment]
Hi @mattray by the looks of things the project is really active so no how busy you must beut have you been able to replicate this issue. The dashboard is super useful when it was working so any progress on this would be useful

**Comment by mattray** [comment]
Sorry, I've been swamped on other projects. A couple of folks brought it up at KubeCon that they'd be interested in working on it, but I haven't heard from anyone else yet. I'm not a Grafana expert by any means, so if someone's interested and wants to take this feel free. I'll try to circle back to this soon.

**Comment by sossickd** [comment]
@dwbrown2 di yo resolve a similar issue here?

https://github.com/kubecost/cost-analyzer-helm-chart/issues/303

Could the same logic be applied?

**Comment by dwbrown2** [comment]
@sossickd I'd have to dig in to share for sure. I'm unfortunately tied up on other projects right now, would love to extra help if others are able to review. Will do my best to circle back when free.

**Comment by sossickd** [comment]
@dwbrown2, @mattray OK found the issue, this was caused when running the opencost deployment with more than one replica.

Created a PR.

https://github.com/opencost/opencost-helm-chart/pull/157

This adds a variable to filter on pod, amended each pane that had the many-to-many error and filtered on the pod label.

Not too sure if this is the best solution but fixed it in my case.

**Comment by andriktr** [comment]
Hmm... it sounds strange as I'm running opencost with single replica and still have same issues.

**Comment by sossickd** [comment]
@andriktr can you copy and paste one of the errors in a code snippet from one of the broken panes so i can see if its the same issue i was experiencing

**Comment by andriktr** [comment]
Errors I got are in the very first post of this issue.

**Comment by sossickd** [comment]
@andriktr would you mind pasting into a code snippet so i can copy easier?

**Comment by andriktr** [comment]
Sure:

Here is the error output for Top 20 by Namespace dashboard:

```
Status: 500. Message: execution: found duplicate series for the match group {instance="10.162.208.9:9003"} on the right hand-side of the operation: [{arch="amd64", container="opencost", endpoint="http", exported_instance="aks-default-29533205-vmss00000k", instance="10.162.208.9:9003", instance_type="Standard_D4s_v3", job="opencost", namespace="opencost", node="aks-default-29533205-vmss00000k", pod="opencost-858f6d4597-rr644", provider_id="azure:///subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/aks-nodes-west-dev/providers/Microsoft.Compute/virtualMachineScaleSets/aks-default-29533205-vmss/virtualMachines/20", region="westeurope", service="opencost"}, {arch="amd64", container="opencost", endpoint="http", exported_instance="aks-default-29533205-vmss00000i", instance="10.162.208.9:9003", instance_type="Standard_D4s_v3", job="opencost", namespace="opencost", node="aks-default-29533205-vmss00000i", pod="opencost-858f6d4597-rr644", provider_id="azure:///subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/aks-nodes-west-dev/providers/Microsoft.Compute/virtualMachineScaleSets/aks-default-29533205-vmss/virtualMachines/18", region="westeurope", service="opencost"}];many-to-many matching not allowed: matching labels must be unique on one side
```

**Comment by sossickd** [comment]
Can you open up prometheus and enter in this query:

```
topk( 30, 
  sum(sum(container_memory_allocation_bytes{namespace=~"$namespace"}) by (container,instance,pod) * on(instance) group_left() (
				node_ram_hourly_cost{pod=~".*opencost.*",pod=~"opencost-858f6d4597-rr644"} / 1024 / 1024 / 1024
				+ on(node,instance_type,pod) group_left()
					label_replace
					(
						kube_node_labels{}, "instance_type", "$1", "label_node_kubernetes_io_instance_type", "(.*)"
					) * 0
			)
  + 
  sum(container_cpu_allocation{namespace=~"$namespace"}) by (container,instance,pod) * on(instance) group_left() (
	  			node_cpu_hourly_cost{pod=~".*opencost.*",pod=~"opencost-858f6d4597-rr644"} + on(node,instance_type,pod) group_left()
		  			label_replace
		  			(
		  				kube_node_labels{}, "instance_type", "$1", "label_node_kubernetes_io_instance_type", "(.*)"
		  			) * 0
		  	)) by (container)
)
```

Do you get the many-to-many matching not allowed: matching labels must be unique on one side error?

**Comment by andriktr** [comment]
I receive no data actually for this particular query: 
<img width="1512" alt="image" src="https://github.com/opencost/opencost-helm-chart/assets/25537180/1c4413db-00b2-44b2-855f-f0daf2c177d3">

**Comment by sossickd** [comment]
OK looks at the error a bit further it looks like your issue maybe slightly different to mine.

```
[{arch="amd64", 
container="opencost", 
endpoint="http", 
exported_instance="aks-default-29533205-vmss00000k", 
instance="10.162.208.9:9003", 
instance_type="Standard_D4s_v3", 
job="opencost", 
namespace="opencost", 
node="aks-default-29533205-vmss00000k", 
pod="opencost-858f6d4597-rr644", 
provider_id="azure:///subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/aks-nodes-west-dev/providers/Microsoft.Compute/virtualMachineScaleSets/aks-default-29533205-vmss/virtualMachines/20", 
region="westeurope", 
service="opencost"}, 

{arch="amd64", 
container="opencost", 
endpoint="http", 
exported_instance="aks-default-29533205-vmss00000i",
instance="10.162.208.9:9003", 
instance_type="Standard_D4s_v3", 
job="opencost", 
namespace="opencost", 
node="aks-default-29533205-vmss00000i", 
pod="opencost-858f6d4597-rr644", 
provider_id="azure:///subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/aks-nodes-west-dev/providers/Microsoft.Compute/virtualMachineScaleSets/aks-default-29533205-vmss/virtualMachines/18", 
region="westeurope", 
service="opencost"}]
```
Why is the opencost pod returning the fact that it resides on different exported_instance, node and provider_id?

**Comment by sossickd** [comment]
@andriktr can you tun the following query in prometheus and paste the return in a code snippet.

```
node_ram_hourly_cost
```

**Comment by andriktr** [comment]
Hi, 
Node name for the opencost could change when opencost pod is rescheduled to another node for one or another reason i.e. cluster maintenance, workload rebalancig with descheduler, cluster upgrade, autoscaling etc. 
<img width="1124" alt="image" src="https://github.com/opencost/opencost-helm-chart/assets/25537180/bfb767cb-6ea9-429d-ab93-4bcb58c139a5">

And here is the error from same cluster

```
Status: 500. Message: execution: found duplicate series for the match group {instance="10.162.208.9:9003"} on the right hand-side of the operation: [{arch="amd64", container="opencost", endpoint="http", exported_instance="aks-default-29533205-vmss00000k", instance="10.162.208.9:9003", instance_type="Standard_D4s_v3", job="opencost", namespace="opencost", node="aks-default-29533205-vmss00000k", pod="opencost-858f6d4597-rr644", provider_id="azure:///subscriptions/000000-0000-0000-0000-00000000000/resourceGroups/aks-nodes-west-dev/providers/Microsoft.Compute/virtualMachineScaleSets/aks-default-29533205-vmss/virtualMachines/20", region="westeurope", service="opencost"}, {arch="amd64", container="opencost", endpoint="http", exported_instance="aks-default-29533205-vmss00000i", instance="10.162.208.9:9003", instance_type="Standard_D4s_v3", job="opencost", namespace="opencost", node="aks-default-29533205-vmss00000i", pod="opencost-858f6d4597-rr644", provider_id="azure:///subscriptions/000000-0000-0000-0000-00000000000/resourceGroups/aks-nodes-west-dev/providers/Microsoft.Compute/virtualMachineScaleSets/aks-default-29533205-vmss/virtualMachines/18", region="westeurope", service="opencost"}];many-to-many matching not allowed: matching labels must be unique on one side
```

Mentioned query returns the following:
<img width="2040" alt="image" src="https://github.com/opencost/opencost-helm-chart/assets/25537180/439ec212-c361-49e4-9bc4-1dbc6b02a4a0">

**Comment by sossickd** [comment]
OK this is different from what i am seeing. In my case the instance value matches the node value.

![image](https://github.com/opencost/opencost-helm-chart/assets/16937121/0657b2a8-2fa3-4229-b4ef-2dbe4cfadab9)

Are you using any relabelings of metrics? Can you determine what `10.162.208.9:9003` refers too? From what i can see 10.162.208.9 isn't a nodes ip address, is it the ip address of the opencost pod?

Also what version of opencost are you using?

**Comment by andriktr** [comment]
Yes, 10.162.208.9:9003 is the opencost pod ip.  Version is `1.107.0`, but I saw same in earlier versions as well.

**Comment by sossickd** [comment]
@andriktr are you doing any relabelings of metrics? Trying ti get my head around why you are getting a exported_instance metric and the instance metric is being transformed to 10.162.208.9:9003

**Comment by andriktr** [comment]
Hey we do not do any relabelings of metrics. I have my own helm chart but in general it more less same as official + some addons for AAD Pod Identity:

```yaml
serviceAccount:
  create: true
  annotations: {}
  # eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/eksctl-opencost
  automountServiceAccountToken: true

annotations: {}
  #azure.workload.identity/inject-proxy-sidecar: "true"

service:
  annotations: {}
  labels: {}
  type: ClusterIP

opencost:
  exporter:
    # The GCP Pricing API requires a key. This is supplied just for evaluation.
    # cloudProviderApiKey: 'asdfasdfasdf'
    # Default cluster ID to use if cluster_id is not set in Prometheus metrics.
    defaultClusterId: "aks-experimental"
    image:
      registry: redacted
      repository: kubecost-cost-model
      tag: prod-1.107.0
    resources:
      requests:
        cpu: '10m'
        memory: '55M'
      limits:
        cpu: '999m'
        memory: '1G'
    extraEnv:
      {}
      # FOO: BAR

  metrics:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: 'kube-prometheus-stack'
      ## The label to use to retrieve the job name from.
      ## jobLabel: "app.kubernetes.io/name"
      namespace: 'kube-prometheus-stack'
      namespaceSelector: {}
      ## Default: scrape .Release.Namespace only
      ## To scrape all, use the following:
      ## namespaceSelector:
      ##   any: true
      scrapeInterval: 30s
      # honorLabels: true
      targetLabels: []
      relabelings: []
      metricRelabelings: []

  prometheus:
    # username:
    # password:
    external:
      enabled: false
      url: 'https://mimir-dev-push.infra.alto.com/prometheus'
    internal:
      enabled: true
      serviceName: kube-prometheus-stack-prometheus
      namespaceName: kube-prometheus-stack
      port: 9090

  ui:
    enabled: true
    image:
      registry: redacted
      repository: opencost-ui
      tag: prod-1.107.0
    resources:
      requests:
        cpu: '10m'
        memory: '55M'
      limits:
        cpu: '999m'
        memory: '1G'

  tolerations: []

# Baltic IF Custom Values
customAzureConfig: 
  enabled: true
  azureTenantId: "redacted"
  azureSubscriptionId: "redacted"

azurePodIdentity:
  enabled: true
  azureIdentity:
    name: opencost-identity
    resourceID: "redacted"
    clientID: "redacted"
  azureIdentityBinding:
    name: opencost-identity-binding
    selector: opencost-identity

azureWorkloadIdentity:
  enabled: false
  clientID: ""

ingress:
  enabled: true
  annotations: {}
  labels: {}
  ingress-class: internal-nginx
  hosts:
    - host: opencost-experimental.eu
      paths:
      - path: /
        pathType: ImplementationSpecific
        serviceName: opencost
        servicePort: 9090
  tls:
  - hosts:
    - opencost-experimental.eu
    secretName: ""
```

**Comment by Dkaykay** [comment]
Hey, 
are there any updates on this issue? i am also seeing the "duplicate" issue in e.g. Top 20 by Namespace:

```
Status: 500. Message: execution: found duplicate series for the match group {instance_type="c5n.large", node="ip-10-250-0-163.eu-central-1.compute.internal"} on the right hand-side of the operation: [{cluster="cluster01-dmi", clusterType="dmi", instance="kube-state-metrics.monitoring.svc:8080", instance_type="c5n.large", job="kube-state-metrics", k8sType="aws", label_beta_kubernetes_io_arch="amd64", label_beta_kubernetes_io_instance_type="c5n.large", label_beta_kubernetes_io_os="linux", label_cluster_update_csi_sap_com_anytime="1", label_failure_domain_beta_kubernetes_io_region="eu-central-1", label_failure_domain_beta_kubernetes_io_zone="eu-central-1c", label_hana_cloud_workload_class_edge="1", label_kubernetes_io_arch="amd64", label_kubernetes_io_hostname="ip-10-250-0-163.eu-central-1.compute.internal", label_kubernetes_io_os="linux", label_networking_gardener_cloud_node_local_dns_enabled="false", label_node_kubernetes_io_instance_type="c5n.large", label_node_kubernetes_io_role="node", label_topology_ebs_csi_aws_com_zone="eu-central-1c", label_topology_kubernetes_io_region="eu-central-1", label_topology_kubernetes_io_zone="eu-central-1c", label_worker_garden_sapcloud_io_group="edge", label_worker_gardener_cloud_cri_name="containerd", label_worker_gardener_cloud_kubernetes_version="1.26.11", label_worker_gardener_cloud_pool="edge", landscape="cluster01", node="ip-10-250-0-163.eu-central-1.compute.internal", project="hc-dev", prometheus="monitoring/prometheus", region="eu-central-1"}, {cluster="cluster01-dmi", clusterType="dmi", container="opencost", endpoint="http", instance="100.96.10.107:9003", instance_type="c5n.large", job="opencost", k8sType="aws", label_beta_kubernetes_io_arch="amd64", label_beta_kubernetes_io_instance_type="c5n.large", label_beta_kubernetes_io_os="linux", label_cluster_update_csi_sap_com_anytime="1", label_failure_domain_beta_kubernetes_io_region="eu-central-1", label_failure_domain_beta_kubernetes_io_zone="eu-central-1c", label_hana_cloud_workload_class_edge="1", label_kubernetes_io_arch="amd64", label_kubernetes_io_hostname="ip-10-250-0-163.eu-central-1.compute.internal", label_kubernetes_io_os="linux", label_networking_gardener_cloud_node_local_dns_enabled="false", label_node_kubernetes_io_instance_type="c5n.large", label_node_kubernetes_io_role="node", label_topology_ebs_csi_aws_com_zone="eu-central-1c", label_topology_kubernetes_io_region="eu-central-1", label_topology_kubernetes_io_zone="eu-central-1c", label_worker_garden_sapcloud_io_group="edge", label_worker_gardener_cloud_cri_name="containerd", label_worker_gardener_cloud_kubernetes_version="1.26.11", label_worker_gardener_cloud_pool="edge", landscape="cluster01", namespace="opencost", node="ip-10-250-0-163.eu-central-1.compute.internal", pod="opencost-5f7549c7f8-8kxtf", project="hc-dev", prometheus="monitoring/prometheus", region="eu-central-1", service="opencost"}];many-to-many matching not allowed: matching labels must be unique on one side
```

Any hints on how to solve / work around?

Thanks!

**Comment by andriktr** [comment]
Most probably main reason here is that opencost  duplicates kube-state-metrics (uses same names) for it's metrics

<img width="1730" alt="image" src="https://github.com/opencost/opencost-helm-chart/assets/25537180/66baa837-dbc3-403f-b8af-04ba6deeb0d8">

To check u can try to simply search for kube_node_info metrics in grafana explorer you probably will see it doubled with additional instances related to opencost. 

P.S. i have tried to adjust setting mentioned in https://www.opencost.io/docs/installation/helm#example-configuration
```yaml
...
opencost:
  exporter:
    extraEnv:
      EMIT_KSM_V1_METRICS: "false"
      EMIT_KSM_V1_METRICS_ONLY: "true"
```
however for some reason this not worked, so I ended up with uninstalling opencost and switching to aks-cost-analysis addon which is actually also based on opencost :)
