### ISSUE TITLE
UI not accessible with path-based ingress

### ISSUE THREAD

**Issue by niklastanner** [opencost/opencost-helm-chart#148]
Using a path based ingress is possible, but the OpenCost UI itself does not load as it ignores the path defined within the ingress:

values.yaml
```
opencost:
  ui:
    ingress:
      enabled: true
      hosts:
        - host: test.intern.ch
          paths:
            - /opencost
      tls:
        - hosts:
            - test.intern.ch
```

The page is served at test.intern.ch/opencost but it serves an empty page as the index.js and other resources result in 404 as it is trying to load from `test.intern.ch/index.js` which is not a valid path.

Maybe this could be solved by providing the `BASE_URL_OVERRIDE` environment variable to the ui container. But I'm not quite sure. See the [opencost/ui Github page](https://github.com/opencost/opencost/tree/develop/ui#overriding-the-base-api-url) for reference. The current `deployment.yaml` does not allow to add additional env-values. This could be solved by adding the following block to the opencost-ui container in the `deployment.yaml`:

```
{{- with .Values.opencost.ui.extraEnv }}
env:
{{- toYaml . | nindent 10 }}
{{- end }}
```
