### ISSUE TITLE
opencost:  tls failed to verify certificate x509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by rabahbrahami** [opencost/opencost-helm-chart#162]
I encounter a problem with the configuration of opencost with the configuration of a prometheus external which is exposed in http or https, I tried with http but there is a redirection to https which is done automatically.
```
  prometheus:
    external:
      # -- Use external Prometheus (eg. Grafana Cloud)
      enabled: true
      # -- External Prometheus url
      url: "http://prometheus.....com"
    internal:
      enabled: false
```
Error:

`tls: failed to verify certificate: x509: certificate signed by unknown authority'`

The only solution is to have the possibility to put `InsecureSkipVerify` in input as an environment variable since for the moment the values cannot be overloaded.
