### ISSUE TITLE
UI Ingress not working

### ISSUE THREAD

**Issue by charalamm** [opencost/opencost-helm-chart#164]
Hi, thank you for this very useful Helm chart!

I am having issues with exposing the opencost UI with a domain name. When connecting to the URL that is supposed to load the UI, there is a white page and in the console there is the error `index.9d46bb91.js:1 
 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
index.runtime.b478a79e.js:1 
 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

At the same time the port forwarded UI works fine and other services with UI also work.

My value overrides:
```
      opencost:
        exporter:
          env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: "http://prometheus-grafana-kube-pr-prometheus.monitoring.svc:9090"
            - name: CLOUD_PROVIDER_API_KEY
              value: "<>" # The GCP Pricing API requires a key. This is supplied just for evaluation.}}/daily_export.csv"
        ui:
          enabled: true
          ingress:
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/use-regex: "true"
            enabled: true
            hosts:
              - host: "subomain.domain.com"
                paths:
                  - "/opencost(/|$)(.*)"
            tls:
              - secretName: tls-secret
                 hosts:
                   - "subomain.domain.com"
```

I see this is because of the way the UI is build though. Is that correct? If so I will open a new issue in Opencost repo
https://stackoverflow.com/questions/72070748/failed-to-load-module-script-expected-a-javascript-module-script-but-the-server
