### ISSUE TITLE
Error fetching Savings Plan Data: QueryAthenaPaginated: athena configuration incomplete

### ISSUE THREAD

**Issue by prasoon-pxc** [opencost/opencost-helm-chart#166]
I have installed opencost and then try to integrate AWS cloud cost on it , I have followed all the steps from below doc to setup different things:

- Setup CUR
https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations#cost-and-usage-report-integration
- Setup Athena
https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations#step-2-setting-up-athena
- Setup IAM Permissions by following file:
```
module "iam_eks_role" {
  source    = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  role_name = "opencost"
  version   = "5.33.0"

  role_policy_arns = {
    policy = module.iam_policy.arn
  }

  oidc_providers = {
    one = {
      provider_arn               = local.kube_info["oidc_provider_arn"]
      namespace_service_accounts = ["opencost:development-opencost"]
    }

  }
}

module "iam_policy" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-policy"
  version = "5.33.0"

  name        = "opencost_policy"
  path        = "/"
  description = "used for opencost tools"

  policy = jsonencode({

    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Sid" : "AthenaAccess",
        "Effect" : "Allow",
        "Action" : [
          "athena:*"
        ],
        "Resource" : [
          "*"
        ]
      },
      {
        "Sid" : "ReadAccessToAthenaCurDataViaGlue",
        "Effect" : "Allow",
        "Action" : [
          "glue:GetDatabase*",
          "glue:GetTable*",
          "glue:GetPartition*",
          "glue:GetUserDefinedFunction",
          "glue:BatchGetPartition"
        ],
        "Resource" : [
          "arn:aws:glue:*:*:catalog",
          "arn:aws:glue:*:*:database/athenacurcfn*",
          "arn:aws:glue:*:*:table/athenacurcfn*/*"
        ]
      },
      {
        "Sid" : "AthenaQueryResultsOutput",
        "Effect" : "Allow",
        "Action" : [
          "s3:GetBucketLocation",
          "s3:GetObject",
          "s3:ListBucket",
          "s3:ListBucketMultipartUploads",
          "s3:ListMultipartUploadParts",
          "s3:AbortMultipartUpload",
          "s3:CreateBucket",
          "s3:PutObject"
        ],
        "Resource" : [
          "arn:aws:s3:::aws-athena-query-results-*"
        ]
      },

      {
        "Sid" : "S3ReadAccessToAwsBillingData",
        "Effect" : "Allow",
        "Action" : [
          "s3:Get*",
          "s3:List*"
        ],
        "Resource" : [
          "arn:aws:s3:::opencostrty"
        ]
      },

      {
        "Action" : [
          "organizations:ListAccounts",
          "organizations:ListTagsForResource"
        ],
        "Resource" : [
          "*"
        ],
        "Effect" : "Allow",
        "Sid" : "ReadAccessToAccountTags"
      },
    ]

  })

}
```

--- helm chart values:

```yaml
---
opencost: 
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::28535656734:role/opencost"
  opencost:
   cloudCost:
    enabled: false
   customPricing:
    enabled: true
    provider: aws
    costModel:
     athenaBucketName: "s3://aws-athena-query-results-test-cost"
     athenaRegion: "eu-central-1"
     athenaDatabase: "athenacurcfn_opencost_cur"
     athenaTable: "opencost_cur"
     projectID: "394279423"
   ui:
    enabled: true
    image:
     registry: gcr.io
     repository: kubecost1/opencost-ui
     tag: "cloudcost"
   prometheus:
    internal:  
     enabled: true
     serviceName: prometheus-kube-prometheus-prometheus
     namespaceName: monitor
     port: 9090
   metrics:
    serviceMonitor:
    enabled: true
    namespace: monitor
   exporter:
    defaultClusterId: "default-test-cluster"
    image:
      registry: gcr.io
      repository: kubecost1/opencost
      tag: "cloudcost"
    extraEnv:
      EMIT_KSM_V1_METRICS: "false"
      EMIT_KSM_V1_METRICS_ONLY: "true"
      LOG_LEVEL: error #error
      AWS_PRICING_URL: "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/eu-central-1/index.json"   
  
```

opencost container logs:

```
2024-01-05T08:58:39.23149803Z ERR Failed to lookup reserved instance data: no reservation data available in Athena2024-01-05T08:58:39.231539251Z 
ERR Failed to lookup savings plan data: Error fetching Savings Plan Data: QueryAthenaPaginated: athena configuration incomplete
```
