### ISSUE TITLE
Prometheus values are not being used in the templates

### ISSUE THREAD

**Issue by martinhausio** [opencost/opencost-helm-chart#175]
the values.yaml file shows how to configure the prometheus namespace and service name, but the actual values do not seem to be used anywhere in the templates, resulting in the PROMETHEUS_SERVER_ENDPOINT environment variable to always use the default value: http://prometheus-server.prometheus-system.svc.cluster.local:80

**Comment by mattray** [comment]
Are you sure you're using your local overrides properly? I have the following in my `local.yaml`
```
opencost:
  prometheus:
    internal:
      enabled: true
      serviceName: my-prometheus-server
      namespaceName: prometheus
      port: 80
```

This is getting rendered around https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/templates/_helpers.tpl#L102

and I see

```
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: "http://my-prometheus-server.prometheus.svc.cluster.local:80"
```
when I do a `--dry-run` to see my Helm output
