### ISSUE TITLE
 namespaceSelector label should be kubernetes.io/metadata.name

### ISSUE THREAD

**Issue by zgpcy** [opencost/opencost-helm-chart#197]
### Setup
I enabled network policies to allow traffic only from my prometheus instance:
```
networkPolicies:
  enabled: true
  prometheus:
    namespace: monitoring
    port: 9090
    labels: {}
```
This creates the following network policy:
```
# Source: opencost/templates/networkpolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: opencost-opencost
  namespace: opencost
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: opencost
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: prometheus
        namespaceSelector:
          matchLabels:
            name: monitoring
      ports:
      - port: 9003
  egress:
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: prometheus
        namespaceSelector:
          matchLabels:
            name: monitoring
      ports:
      - port: 9090
```
### Issue
Target is down. Prometheus cannot scrape the opencost pod.

### Custom Fix
According to [docs](https://kubernetes.io/docs/concepts/services-networking/network-policies/#targeting-a-namespace-by-its-name) the label key name should be `kubernetes.io/metadata.name`
#### Current implementation
```
namespaceSelector:
  matchLabels:
    name: monitoring
```

#### Working implementation:
```
namespaceSelector:
  matchLabels:
    kubernetes.io/metadata.name: monitoring
```
