### ISSUE TITLE
Include image digest for containers 

### ISSUE THREAD

**Issue by toscott** [opencost/opencost-helm-chart#214]
Proposal
Explicitly set the image digests in the helm chart, while still allowing users to remove them if desired. 

E.G.
```
opencost:
  exporter:
    image:
      digest: sha256:6aa68e52a24b14ba41f23db08d1b9db1429a1c0300f4c0381ecc2c61fc311a97
```

Why
Without the digest, anyone pulling images directly from the public registry could be at risk of supply chain problems. While existing images tags should not be getting overwritten, without an image digest in the helm chart any repush will automatically propagate out to those users.
