### ISSUE TITLE
Documentation on how to use OpenCost with an existing prometheus installation on OpenShift?

### ISSUE THREAD

**Issue by kastl-ars** [opencost/opencost-helm-chart#226]
Hi all,

I would like to run OpenCost in OpenShift, but am unsure before even starting due to the various options in the `values.yaml` regarding authentication to an external Prometheus.

https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml#L320

Our OpenShift cluster has a thanos-querier service running, that requires authentication using the serviceaccount token. How would I put this into the `values.yaml`?

I figured something like the following could work, but I am not sure if the bearertoken works with a Kubernetes serviceAccount token or needs some other format?

```
  prometheus:
    secret_name: ~
    existingSecretName: my-existing-service-account-token-secret
    username: ""
    username_key: ""
    password: ""
    password_key: ""
    bearer_token: ""
    bearer_token_key: "token" # the key used for the token in the my-existing-service-account-token-secret secret
    external:
      enabled: true
      url: "https://thanos-querier...."
```

Any hints are highly appreciated.

Kind Regards,
Johannes

**Comment by kastl-ars** [comment]
One addition: The service account token should already be mounted inside the pod, as the `automountServiceAccountToken` setting is true. Is there any way to tell the pod to use that file?

Especially as the name of the token secret for the serviceAccount is not predictable, how would I specify this beforehand?

**Comment by AjayTripathy** [comment]
cc @jessegoodier  can someone on your team help get this documented? Seems valuable.

**Comment by jessegoodier** [comment]
> cc @jessegoodier can someone on your team help get this documented? Seems valuable.
Ishaan is working on this. I'm sure it is possible, will look at how other tools are doing it.

**Comment by kastl-ars** [comment]
Any news on this?

**Comment by jessegoodier** [comment]
Yes! https://github.com/opencost/opencost-helm-chart/issues/226
Getting closer. I can't commit to timing though.

**Comment by mittal-ishaan** [comment]
This is completed in https://github.com/opencost/opencost-helm-chart/pull/229

**Comment by kastl-ars** [comment]
Was this included in the last release of this helm-chart?

**Comment by thomasvn** [comment]
The implementation of `KUBE_RBAC_PROXY` and authenticating with an existing Prometheus was fulfilled by https://github.com/opencost/opencost-helm-chart/pull/229 and is available in the latest release. https://github.com/opencost/opencost-helm-chart/releases/tag/1.43.0-helm

@mittal-ishaan Could you help to document the changes you made in #229?

**Comment by kastl-ars** [comment]
Thanks for the clarification @thomasvn !

**Comment by kastl-ars** [comment]
Is there any documentation on how to get the Opencost extra scrape configuration into the OpenShift prometheus?

**Comment by mittal-ishaan** [comment]
You will need to add a label in the opencost release namespace 
```sh
oc label namespace kubecost openshift.io/cluster-monitoring=true
```

and create `serviceMontior` for our opencost service.
Ref: https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html-single/monitoring/index#support-considerations_configuring-the-monitoring-stack

You can refer the below helm values till the time I can get this documented.
```yaml
opencost:
  metrics:
    serviceMonitor:
      enabled: true
  prometheus:
    kubeRBACProxy: true
    createMonitoringClusterRoleBinding: true
    createMonitoringResourceReaderRoleBinding: true
    monitoringServiceAccountName: prometheus-k8s
    monitoringServiceAccountNamespace: openshift-monitoring
    external:
      enabled: true
      url: https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091
  ui:
    extraVolumeMounts:
      - name: empty-var-www
        mountPath: /var/www
      - name: opencost-ui-nginx-config-volume
        mountPath: /etc/nginx/conf.d/default.nginx.conf
        subPath: default.nginx.conf

extraVolumes:
  - name: empty-var-www
    emptyDir: {}
  - name: opencost-ui-nginx-config-volume
    configMap:
      name: opencost-ui-nginx-config
```
Let me know if this does not work for you.

**Comment by kastl-ars** [comment]
Thanks, I'll test it!

**Comment by kastl-ars** [comment]
> Let me know if this does not work for you.

One thing, I had to disable the internal prometheus in addition to enabling the external one:

```
opencost:
[...]
  prometheus:
[...]
    external:
      enabled: true
      url: https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091
    internal:
      enabled: false
```
