### ISSUE TITLE
OpenCost metrics interfere with OpenShift's CPU count for the cluster

### ISSUE THREAD

**Issue by kastl-ars** [opencost/opencost-helm-chart#252]
Similar to #249 , the metrics exported by OpenCost interfere with OpenShift's CPU count.

One one of our clusters, the CPU count visible in OpenShift's "Overview" in the "Dashboard" went from 88 CPUs available to 44 CPUs available, which is the real number, after setting `EMIT_KSM_V1_METRICS` to `false`

```
  opencost:
    metrics:
      serviceMonitor:
        enabled: true
      kubeStateMetrics:
        emitKsmV1Metrics: false
[...]
```

Not sure if this is an issue for the opencost repository rather than for the helm chart one, as I have not gotten OpenCost to work without those v1 metrics. It simply does not show any costs at all.
