### ISSUE TITLE
internal prometheus assumes http, no option for https scheme

### ISSUE THREAD

**Issue by jessegoodier** [opencost/opencost-helm-chart#273]
Need template for scheme. Something like:

```yaml
opencost:
  prometheus:
    internal:
      scheme: http://
```

[code ref](https://github.com/opencost/opencost-helm-chart/blob/886dbf0fdf9c06b2b7a1f6f2759285c5aa892668/charts/opencost/templates/_helpers.tpl#L106)
