### ISSUE TITLE
Allocation service not defined

### ISSUE THREAD

**Issue by karthik-opsera** [opencost/opencost-helm-chart#280]
Deployed opencost helm chart. 
Configured existing Prometheus and configured scrap config.

I can see metrics being scraped into Promethues.

However when opening Opencost UI, getting error "allocation service not defined".

Affected version: v1.115.0

After changing the Opencost UI, image URL in opencost-ui container, UI is loading

**Comment by mittal-ishaan** [comment]
Hi @karthik-opsera 
Thanks for reporting,
looks like a bug is present in 1.115.0 in opencost-ui. Looking into it to get it fixed.
For a temporary solution, you can use the following values to get yourself unblocked for now:
```
opencost:
  ui:
    image:
      fullImageName: ghcr.io/opencost/opencost-ui:1.114.0
```
