### ISSUE TITLE
Add Ingress for UI

### ISSUE THREAD

**Issue by boniek83** [opencost/opencost-helm-chart#32]
Just a basic feature.

**Comment by mattray** [comment]
I worry about adding a default Ingress given the fact there's no auth to use the UI. I do use an Ingress on my home clusters, but I'm still not in favor of it unless someone convinces me otherwise. Also, there are lots of npm warnings with the UI for vulnerabilities, which means we should clean those up before we do this.

**Comment by boniek83** [comment]
You can disable it by default. I don't see the downside.

**Comment by mattray** [comment]
Fair enough. If you want to put together a PR to allow you to enable Ingress for the UI, I'm onboard.

If you don't have an Ingress, here's mine. Not saying it's good, but it works.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opencost-ingress
  namespace: opencost
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opencost
                port:
                  number: 9090
```
