### ISSUE TITLE
Internal prometheus URL doesn't support routePrefix

### ISSUE THREAD

**Issue by usulkies** [opencost/opencost-helm-chart#71]
The kube-prometheus-stack helm chart supports the routePrefix for prometheusSpec.
This means that prometheus endpoint can have a route prefix.
Current code does not support this, but assuming that the internal endpoint always listens on the root path.

https://github.com/opencost/opencost-helm-chart/blob/6ed2eb42ab99d2bc2f699e949a72226a56c6068e/charts/opencost/templates/_helpers.tpl#L78

**Comment by toscott** [comment]
I believe you can leverage the "external" prometheus option to set a more customized url:

```
opencost:
  prometheus:
    external:
      enabled: true
      url: 'http://prometheus.monitoring.svc:9090/custom-path'
```
